### ISSUE TITLE
Error while loadin face recognition skill

### ISSUE THREAD

**Issue by MB2412** [JarbasAl/skill-face-recognition#2]
hey jarbas
I am a beginner in programming and I want to try face recognition skill, but every time I start Mycroft, I get an error while loading face recognition skill 

![screenshot from 2018-04-09 22-55-19](https://user-images.githubusercontent.com/37438093/38525539-a8aac882-3c4a-11e8-8c5d-38ff55b15860.png)
I had already installed, open cv and after checking it works

![screenshot from 2018-04-09 22-57-18](https://user-images.githubusercontent.com/37438093/38525568-bd09029e-3c4a-11e8-9874-42d66f75efb9.png)
 I hope that you can help me to fix this error, thanks

**Comment by JarbasAl** [comment]
can you confirm it works now? install scripts got an overhaul

**Comment by MB2412** [comment]
hey yeah it works for me now
Here is what I did to fix it:
i Changed line #274 to this if score > 0.5:
and  The package is named opencv-python. So on the command line first do workon mycroft then do pip install opencv-python
thanks
