### ISSUE TITLE
where the faces encodings are located?

### ISSUE THREAD

**Issue by MB2412** [JarbasAl/skill-face-recognition#3]
hey jarbas 
sorry for being little bit annoying, but I am wondering how can I access to my faces encodings and can I modify them (I mean none) 
plus is it possible to run this skill offline 
![screenshot from 2018-04-11 21-26-37](https://user-images.githubusercontent.com/37438093/38641571-58d94fc8-3dcf-11e8-9ffe-a558f9824a3f.png)
I didn t figure out what is face_encodings.Fr

**Comment by JarbasAl** [comment]
faces are not saved as pictures, just face encodings (coordinates of key face points) are saved, those are the file named face_encodings.fr, can not be changed manually

the skill runs offline, you need internet for stt however
